name: ghostpass
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0+100

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  catppuccin_flutter: ^1.0.0
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
